### ISSUE TITLE
Wrong dir for output?

### ISSUE THREAD

**Issue by cmkobel** [ssi-dk/bifrost_test_data#1]
I get the following error when running _test_bifrost.sh_
```
...
Downloading and installing bifrost_ariba_plasmidfinder
Connected to:
    Database: bifrost_test
    Host: 127.0.0.1:27017

test_bifrost.sh: line 32: cd: output: No such file or directory
bash: run_script.sh: No such file or directory
```

And there is no _run_script.sh_

I think maybe https://github.com/ssi-dk/bifrost_test_data/blob/2fadb7c95deca10ad86541894487edc73c212465/test_bifrost.sh#L30
should be `cd bifrost_test_output;` instead?

Kindly

**Comment by kimleeng** [comment]
Ah thanks for this. I need to start monitoring my github emails better. Ya I changed to add a dir before hand then didn't update this part.
